web:
  hostname: web
  build: .
  ports:
    - "3000:3000"
  links:
    - "mongo:mongo"
    - "seleniumhub:hub"
    - "statsd:statsd"
  volumes:
    - ./public:/usr/src/app/public
    - ./server:/usr/src/app/server
    - ./client:/usr/src/app/client
    - ./views:/usr/src/app/views
    - ./test:/usr/src/app/test
    - ./package.json:/usr/src/app/package.json
    - ./config.js:/usr/src/app/config.js
    - ./test-output:/usr/src/app/test-output
mongo:
  image: mongo
  environment:
    - AUTH=no
  ports:
   - "27017:27017"
  volumes:
    - ./data/db:/data/db
dynamo:
  image: amazon/dynamodb-local
  ports:
    - "8000:8000"
  command: -jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data/
  volumes:
    - ./dynamodb_data:/home/dynamodblocal/data
statsd:
  image: hopsoft/graphite-statsd
  ports:
    - "3002:80"
    - "2003:2003"
    - "8125:8125/udp"
grafana:
  image: grafana/grafana
  links:
    - statsd
  ports:
    - "4001:3000"
seleniumhub:
  image: selenium/hub
chromenode:
  image: selenium/node-chrome
  volumes:
    - /dev/shm:/dev/shm
  links:
    - "seleniumhub:hub"
    - "web:web"
