version: '2'
services:
  web:
    hostname: web
    build:
      context: .
      dockerfile: server/Dockerfile.prod
    image: coupling-prod
    ports:
      - "3000:3000"
    links:
      - "mongo:mongo"
  mongo:
    image: mongo
    environment:
      - AUTH=no
    volumes:
      - ./data/db:/data/db
