version: 2
jobs:
  build:
    docker:
      - image: openjdk:8-jre-slim
      - image: mongo:latest
      - image: selenium/standalone-chrome
    environment:
      SELENIUM_ADDRESS: http://localhost:4444/wd/hub
    steps:
      - checkout
      - restore_cache:
          key: coupling-cache-4-{{ .Branch }}
      - run: "./gradlew yarn"
      - run: "./gradlew yarn_cache_dir"
      - save_cache:
          key: coupling-cache-4-{{ .Branch }}
          paths:
            - "~/.gradle"
            - "node_modules"
      - run: "./gradlew test endToEndTest"
      - store_artifacts:
          path: test-output
      - store_test_results:
          path: test-output
      - persist_to_workspace:
          root: ./
          paths:
            - "*"
  deploy-prod:
    docker:
      - image: openjdk:8-jre-slim
    steps:
      - attach_workspace:
          at: ./
      - restore_cache:
          key: coupling-cache-4-{{ .Branch }}
      - setup_remote_docker
      - run: "./gradlew buildProductionImage pushProductionImage"
  notify-aws:
    docker:
      - image: mikesir87/aws-cli
    environment:
      AWS_DEFAULT_REGION: us-east-1
    steps:
      - run: "aws ecs update-service --service Coupling-service --force-new-deployment"
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy-prod:
          requires:
            - build
          filters:
            branches:
              only: master
      - notify-aws:
          requires:
            - deploy-prod