service: coupling

provider:
  name: aws
  runtime: nodejs12.9.0
  stage: dev
  region: us-east-1

functions:
  app:
    handler: build/executable/app.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
    environment:
      NODE_PATH: "build/node_modules_imported"
plugins:
  - serverless-offline